dist: trusty
language: php
os: linux

php:
    - 7.2
    - 7.3
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini
    - pecl install pcov
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install

script:
    - ./vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -B $TRAVIS_BRANCH

jobs:
    include:
    -   stage: phpstan
        script: ./vendor/bin/phpstan analyse
    -   stage: infection
        script: ./vendor/bin/infection --no-progress

